using System;

public class DailyWeather
{
    public string STATION { get; set; }
    public string NAME { get; set; }
    public double LATITUDE { get; set; }
    public double LONGITUDE { get; set; }
    public double ELEVATION { get; set; }
    public DateTime DATE { get; set; }
    public double? AWND { get; set; }
    public string AWND_ATTRIBUTES { get; set; }
    public int? FMTM { get; set; }
    public string FMTM_ATTRIBUTES { get; set; }
    public int? PGTM { get; set; }
    public string PGTM_ATTRIBUTES { get; set; }
    public double? PRCP { get; set; }
    public string PRCP_ATTRIBUTES { get; set; }
    public double? SNOW { get; set; }
    public string SNOW_ATTRIBUTES { get; set; }
    public double? SNWD { get; set; }
    public string SNWD_ATTRIBUTES { get; set; }
    public double? TAVG { get; set; }
    public string TAVG_ATTRIBUTES { get; set; }
    public double? TMAX { get; set; }
    public string TMAX_ATTRIBUTES { get; set; }
    public double? TMIN { get; set; }
    public string TMIN_ATTRIBUTES { get; set; }
    public double? TSUN { get; set; }
    public string TSUN_ATTRIBUTES { get; set; }
    public int? WDF2 { get; set; }
    public string WDF2_ATTRIBUTES { get; set; }
    public int? WDF5 { get; set; }
    public string WDF5_ATTRIBUTES { get; set; }
    public double? WSF2 { get; set; }
    public string WSF2_ATTRIBUTES { get; set; }
    public double? WSF5 { get; set; }
    public string WSF5_ATTRIBUTES { get; set; }
    public int? WT01 { get; set; }
    public string WT01_ATTRIBUTES { get; set; }
    public int? WT02 { get; set; }
    public string WT02_ATTRIBUTES { get; set; }
    public int? WT03 { get; set; }
    public string WT03_ATTRIBUTES { get; set; }
    public int? WT04 { get; set; }
    public string WT04_ATTRIBUTES { get; set; }
    public int? WT05 { get; set; }
    public string WT05_ATTRIBUTES { get; set; }
    public int? WT07 { get; set; }
    public string WT07_ATTRIBUTES { get; set; }
    public int? WT08 { get; set; }
    public string WT08_ATTRIBUTES { get; set; }
    public int? WT10 { get; set; }
    public string WT10_ATTRIBUTES { get; set; }
    public int? WT11 { get; set; }
    public string WT11_ATTRIBUTES { get; set; }
    public int? WT13 { get; set; }
    public string WT13_ATTRIBUTES { get; set; }
    public int? WT14 { get; set; }
    public string WT14_ATTRIBUTES { get; set; }
    public int? WT16 { get; set; }
    public string WT16_ATTRIBUTES { get; set; }
    public int? WT18 { get; set; }
    public string WT18_ATTRIBUTES { get; set; }
    public int? WT21 { get; set; }
    public string WT21_ATTRIBUTES { get; set; }
    public int? WV01 { get; set; }
    public string WV01_ATTRIBUTES { get; set; }
    public int? WV03 { get; set; }
    public string WV03_ATTRIBUTES { get; set; }
}
